#!/usr/bin/env python3
"""Generate docker-compose extra_hosts overrides for cross-VM name resolution.

Mode "cb"  -> token-services/docker-compose.net.yaml
              (adds owner{k}.sworna.example.com -> bank IP to auditor/issuer)
Mode "bank"-> token-services/docker-compose.bank.net.yaml
              (adds orderer/auditor/issuer -> CB IP and other owners -> their
              bank IP to the owner service)

Env:
  SWORNA_OWNERS           space-separated owner node list (default "owner1 owner2")
  SWORNA_CB_HOST          CB host IP (bank mode)
  SWORNA_OWNER_<NAME>_HOST  bank VM IP for each owner (e.g. SWORNA_OWNER_OWNER1_HOST)
"""
import os
import socket
import sys

MODE = sys.argv[1] if len(sys.argv) > 1 else "cb"
OUT = sys.argv[2] if len(sys.argv) > 2 else ""


def detect_cb_ip() -> str:
    """Best-effort IP of this host that other VMs can reach.

    Set SWORNA_CB_HOST explicitly (e.g. the Tailscale IP) when the default
    route interface is not the one the banks use.
    """
    ip = os.environ.get("SWORNA_CB_HOST")
    if ip:
        return ip
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("10.255.255.255", 1))  # no packets sent; picks the route src
        return s.getsockname()[0]
    except OSError:
        try:
            return socket.gethostbyname(socket.gethostname())
        except OSError:
            return "127.0.0.1"

owners = [o for o in os.environ.get("SWORNA_OWNERS", "").split() if o]


def owner_host(node: str) -> str:
    return os.environ.get(f"SWORNA_OWNER_{node.upper()}_HOST", "")


def req(var: str) -> str:
    v = os.environ.get(var, "")
    if not v:
        print(f"gen-net-overrides: {var} not set", file=sys.stderr)
        sys.exit(1)
    return v


def render(services: dict) -> str:
    parts = ["# Generated by scripts/gen-net-overrides.py -- do not edit by hand.\n", "services:"]
    for svc, hosts in services.items():
        parts.append(f"  {svc}:")
        parts.append("    extra_hosts:")
        for h in hosts:
            parts.append(f'      - "{h}"')
    return "\n".join(parts) + "\n"


if MODE == "cb":
    hosts = []
    for o in owners:
        ip = owner_host(o)
        if ip:
            hosts.append(f"{o}.sworna.example.com:{ip}")
            # Map owner1 -> bank1, owner2 -> bank2
            k = o.removeprefix("owner")
            hosts.append(f"peer0.bank{k}.sworna.example.com:{ip}")
    cb_ip = detect_cb_ip()
    hosts.extend([
        f"orderer.sworna.example.com:{cb_ip}",
        f"peer0.centralbank.sworna.example.com:{cb_ip}",
        f"auditor.sworna.example.com:{cb_ip}",
        f"issuer.sworna.example.com:{cb_ip}",
    ])
    body = render({"auditor": hosts, "issuer": hosts})
else:
    cb = req("SWORNA_CB_HOST")
    hosts = [
        f"orderer.sworna.example.com:{cb}",
        f"peer0.centralbank.sworna.example.com:{cb}",
        f"ca.centralbank.sworna.example.com:{cb}",
        f"auditor.sworna.example.com:{cb}",
        f"issuer.sworna.example.com:{cb}",
    ]
    for o in owners:
        ip = owner_host(o)
        if ip:
            hosts.append(f"{o}.sworna.example.com:{ip}")
            k = o.removeprefix("owner")
            hosts.append(f"peer0.bank{k}.sworna.example.com:{ip}")
    body = render({"owner": hosts})

if OUT:
    with open(OUT, "w") as f:
        f.write(body)
else:
    sys.stdout.write(body)